global:
  env: staging
  ingressclass: staging
appName: wee-api
namespace: staging

serviceport: 80
targetport: 5007

maxReplicas: 5
minReplicas: 1


subnet: subnet-2568bb5e,subnet-c6bbe0ae,subnet-ae8e06e2
LBname: staging-eks-lbingress

dnsname: wee-eks.bnking.in

healthPath: /actuator/health/readiness

image:
  repository: 887417737466.dkr.ecr.ap-south-1.amazonaws.com/wee-api-staging
  tag: latest

resources:
  requests:
    cpu: 1
    memory: "1Gi"
  limits:
    cpu: 2
    memory: "1.5Gi"
