global:
  env: develop
  ingressclass: staging
appName: wee-api
namespace: develop

serviceport: 80
targetport: 5007

maxReplicas: 10
minReplicas: 1


dnsname: wee.dev.bnking.in
subnet: subnet-2568bb5e,subnet-c6bbe0ae,subnet-ae8e06e2
LBname: develop-eks-lbingress

image:
  name: 887417737466.dkr.ecr.ap-south-1.amazonaws.com/wee-api-develop
  tag: latest
  
