global:
  env: production
  ingressclass: production
appName: wee-api
namespace: production

serviceport: 80
targetport: 5007

maxReplicas: 10
minReplicas: 1

subnet: subnet-06a741cebaf0f7819,subnet-06e90286ced3c92b3,subnet-026043a113ecb3b3a
LBname: production-eks-lbingress

dnsname: wee.bnking.in

healthPath: /actuator/health/readiness

image:
  repository: 887417737466.dkr.ecr.ap-south-1.amazonaws.com/wee-api-prod
  tag: latest
  
resources:
  requests:
    cpu: 1
    memory: "1Gi"
  limits:
    cpu: 2
    memory: "1.5Gi"
