global:
  env: preprod
  ingressclass: production
appName: wee-api
namespace: preprod

serviceport: 80
targetport: 5007

maxReplicas: 5
minReplicas: 1

dnsname: wee.preprod.bnking.in
subnet: subnet-06a741cebaf0f7819,subnet-06e90286ced3c92b3,subnet-026043a113ecb3b3a
LBname: preprod-eks-lbingress

healthPath: /actuator/health/readiness

image:
  repository: 887417737466.dkr.ecr.ap-south-1.amazonaws.com/wee-api-preprod
  tag: latest

acm: arn:aws:acm:ap-south-1:887417737466:certificate/66ba8269-6c84-4702-8bf3-e2d583b059d6

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "1Gi"