apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appName  }}
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable  }}
  selector:
    matchLabels:
       access: {{ .Values.appName  }}
       appname: {{ .Values.appName  }}