apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.appName }}-{{ .Values.global.env  }}-externalsecret"
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.appName }}-{{ .Values.global.env  }}-secret"
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /{{ .Values.global.env  }}/{{ .Values.appName }}