apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    access: "{{ .Values.appName }}-service"
    appname: {{ .Values.appName  }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.healthPath }}

spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.serviceport }}
    protocol: TCP
    targetPort: {{ .Values.targetport }}
  selector:
    access: {{ .Values.appName }}
    appname: {{ .Values.appName  }}