global:
  env: develop
  ingressclass: staging
appName: comms-service
namespace: develop


serviceport: 80
targetport: 8080

maxReplicas: 1
minReplicas: 1

subnet: subnet-0ac88ae5988e8e023,subnet-08b07ee584a48cc64,subnet-01ab2cb12cacf1209
LBname: develop-magnet-ingress

hosts: '*.api.magnetapp.in'
healthPath: /comms-service/actuator/health/readiness


image:
  repository: 542649758539.dkr.ecr.ap-south-1.amazonaws.com/comms-service-develop
  tag: latest

resources:
  requests:
    cpu: "200m"
    memory: "600Mi"
  limits:
    cpu: 1
    memory: "2Gi"
