global:
  env: preprod
  ingressclass: production
appName: comms-service
namespace: preprod

serviceport: 80
targetport: 8080

maxReplicas: 5
minReplicas: 1

subnet: subnet-06a741cebaf0f7819,subnet-06e90286ced3c92b3,subnet-026043a113ecb3b3a
LBname: preprod-eks-lbingress

hosts: "*.preprod.zetapp.in"
dnsname: comms-service.preprod.zetapp.in

healthPath: /comms-service/actuator/health/readiness


image:
  repository: 887417737466.dkr.ecr.ap-south-1.amazonaws.com/comms-service-preprod
  tag: latest

resources:
  requests:
    cpu: "200m"
    memory: "600Mi"
  limits:
    cpu: 1
    memory: "2Gi"
